## plates to run ##

# PJ's plates are [1,2,3]
# Brendan's plates are [4,5,6,7,8]
# N.B. some rules may not work properly for PJ's plates due to
# different sample naming conventions compared to Brendan's plates

plates: [4,5,6,7,8]

## restriction enzymes for process_radtags ##

renz_1: nheI
renz_2: ecoRI

## paths to original compressed genome files from Richard ##

genome_data:
    CM: genomes/Cmimosae_FINAL_VER2.1.fasta.gz
    CN: genomes/Cnig.1.fasta.gz
    TP: genomes/Tpen_r3.1.fasta.gz

## which genome (value) to use for mapping samples from each ant species (key) ##

genome_mapping:
    CM: CM
    CN: CN
    CS: CM # note mapping to CM genome since we don't presently have a CS genome
    TP: TP

## bowtie2 parameters ##

bowtie2:
    # I think we should expect fragments from about 330bp to 540 bp
    min_length: 300
    max_length: 600
